/* ipTIME A3004NS-dual */

#define BOARD_PID"A3004NS-dual"
#define BOARD_NAME"A3004NS-dual"
#define BOARD_DESC"ipTIME A3004NS-dual Wireless Router"
#define BOARD_VENDOR_NAME"EFM Networks"
#define BOARD_VENDOR_URL"https://iptime.com/"
#define BOARD_MODEL_URL"https://iptime.com/"
#define BOARD_BOOT_TIME30
#define BOARD_FLASH_TIME120

#define BOARD_GPIO_BTN_RESET4
#define BOARD_GPIO_BTN_WPS3
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI
#undef  BOARD_GPIO_LED_SW2G
#undef  BOARD_GPIO_LED_SW5G
#define BOARD_GPIO_LED_POWER18
#undef  BOARD_GPIO_LED_LAN
#undef  BOARD_GPIO_LED_WAN
#define BOARD_GPIO_LED_USB7
#undef  BOARD_GPIO_LED_ROUTER

#define BOARD_HAS_5G_11AC1
#define BOARD_NUM_ANT_5G_TX2
#define BOARD_NUM_ANT_5G_RX2
#define BOARD_NUM_ANT_2G_TX2
#define BOARD_NUM_ANT_2G_RX2
#define BOARD_NUM_ETH_LEDS0
#define BOARD_NUM_ETH_EPHY5
#define BOARD_HAS_EPHY_L10001
#define BOARD_HAS_EPHY_W10001
#define BOARD_NUM_UPHY_USB31
#define BOARD_USB_PORT_SWAP0
